---
title: "dolphin_strandings"
author: "Emma Beyer & Ayoung Kim"
date: "2024-02-27"
output: pdf_document
---

```{r output setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup}
#loading packages
library(tidyverse)
library(ggplot2)
library(GGally)
library(rmarkdown)
#setting WD
setwd("/home/guest/Stat_Modeling_Lab/ENV710Ayoung_Emma")

original_data <- read.csv("dolphins.csv")

#read in data for problems 1-2
strandings <- read.csv("dolphins_cleaned.csv")
#attach data
attach(strandings)

```

## Data Cleaning

```{r cleaning}
#remove NAs
cleaned_strandings <- na.omit(strandings)

#remove unneeded covariates
cleaned_strandings <- subset(cleaned_strandings, select = -c(Shot, Fishery.Interaction, Boat.Collision))

#removing blanks in Age.Class
cleaned_strandings <- cleaned_strandings[!grepl("^\\s*$", cleaned_strandings$Age.Class), ]
#removing unknowns in Age.Class
cleaned_strandings <- cleaned_strandings[!cleaned_strandings$Age.Class %in% c("UNKNOWN"), ]
#removing unknowns in Sex
cleaned_strandings <- cleaned_strandings[!cleaned_strandings$Sex %in% c("UNKNOWN"), ]

#create binary covariate for wind turbine presence in state
cleaned_strandings <- cleaned_strandings %>%
  mutate(turbine_presence = if_else(State %in% c("VA", "NY", "RI", "MA"), 1, 0))

write.csv(cleaned_strandings, "cleaned_strandings", row.names = FALSE)
#strandings_test <- read.csv("cleaned_strandings")


#creating subset using collision observations
subset <- cleaned_strandings[!grepl("^\\s*$", cleaned_strandings$Boat.Collision), ]

#create new csv file for future editing
subset <- subset[!subset$Boat.Collision %in% c("C"), ]

#count of strandings in wind farm states = 6
sum(subset$turbine_presence)

#count of strandings in turbine states = 11
sum(cleaned_strandings$turbine_presence)

```

```{r plots}
#visualizing length and weight by presence of turbines
plot <- ggplot(cleaned_strandings, aes(x = Length, y = Weight, color = as.factor(turbine_presence))) +
  geom_point()
plot

#I like visualizing this data better with box plots
age_class_order <- c("PUP/CALF", "YEARLING", "SUBADULT", "ADULT")

boxplot1 <- ggplot(cleaned_strandings, aes(x = factor(Age.Class, levels = age_class_order), y = Weight)) +
  geom_boxplot(color="skyblue") +
  labs(x = "Age Class", y = "Weight (kg)") +
  ggtitle("Dolphin Weight by Age Class")
boxplot1

boxplot2 <- ggplot(cleaned_strandings, aes(x = factor(Age.Class, levels = age_class_order), y = Length)) +
  geom_boxplot(color="skyblue") +
  labs(x = "Age Class", y = "Length (cm)") +
  ggtitle("Dolphin Length by Age Class")
boxplot2

state_plot <- ggplot(cleaned_strandings, aes(x = State, y = Length)) +
  geom_boxplot(color="skyblue") +
  labs(x = "States", y = "Length (cm)") +
  ggtitle("Dolphin Length by State")
state_plot

state_plot2 <- ggplot(cleaned_strandings, aes(x = State, y = Weight)) +
  geom_boxplot(color="skyblue") +
  labs(x = "States", y = "Weight (kg)") +
  ggtitle("Dolphin Weight by State")
state_plot2

subset_turbines <- filter(cleaned_strandings, State %in% c("VA", "NY", "RI", "MA"))

state_turbines <- ggplot(subset_turbines, aes(x = State, y = Length)) +
  geom_boxplot(color="skyblue") +
  labs(x = "States", y = "Length (cm)") +
  ggtitle("Dolphin Length by State")
state_turbines

state_turbines2 <- ggplot(subset_turbines, aes(x = State, y = Weight)) +
  geom_boxplot(color="skyblue") +
  labs(x = "States", y = "Weight (kg)") +
  ggtitle("Dolphin Length by State")
state_turbines2


#visualizing weight by age class
avg_weight <- aggregate(Weight ~ Age.Class, data = cleaned_strandings, FUN = mean)

avg_weight <- avg_weight[order(-avg_weight$Weight), ]

plot1 <- ggplot(avg_weight, aes(x = reorder(Age.Class, Weight), y = Weight)) +
  geom_bar(stat = "identity", fill = "skyblue") +
  labs(x = "Age Class", y = "Average Weight (kg)") +
  ggtitle("Average Weight by Age Class")
plot1

#visualizing length by age class
avg_lengths <- aggregate(Length ~ Age.Class, data = cleaned_strandings, FUN = mean)

avg_lengths <- avg_lengths[order(-avg_lengths$Length), ]

plot2 <- ggplot(avg_lengths, aes(x = reorder(Age.Class, Length), y = Length)) +
  geom_bar(stat = "identity", fill = "skyblue") +
  labs(x = "Age Class", y = "Average Length") +
  ggtitle("Average Length by Age Class")
plot2

#visualizing sex by presence of turbines
plot3 <- ggplot(cleaned_strandings, aes(x = Sex, fill = factor(turbine_presence))) +
  geom_bar(position = "stack") +
  labs(x = "Sex", y = "Count", fill = "Presence of Turbines") +
  ggtitle("Sex vs Presence of Turbines")
plot3

#visualizing age class by presence of turbines
age_class_order <- c("PUP/CALF", "YEARLING", "SUBADULT", "ADULT")

plot4 <- ggplot(cleaned_strandings, aes(x = factor(Age.Class, levels = age_class_order), fill = factor(turbine_presence))) +
  geom_bar(position = "stack") +
  labs(x = "Age Class", y = "Count", fill = "Presence of Turbines") +
  ggtitle("Age Class vs Presence of Turbines")
plot4

```

```{r models}
#Fitting a regression model (Turbine Presence)
fit_1 <- lm(turbine_presence~1, data = cleaned_strandings_test)
#Summary of the regression model fit_1
summary(fit_1)

#Checking the structure of Cleaned_strandings
str(cleaned_strandings)

#Fitting a regression model (finding the odds of different sex in offshore wind states)
fit_2 <- glm(turbine_presence~Sex,family='binomial', data = cleaned_strandings_test)
#Summary of the regression model fit_2
summary(fit_2)

fit_2 <- glm(turbine_presence~Age.Class,family='binomial', data = cleaned_strandings_test)
#Summary of the regression model fit_2
summary(fit_2)


#Plot for fit_1
fit_2_plot <- ggplot(cleaned_strandings, aes(x =Length, y =turbine_presence)) +
geom_point(shape = 1) +
xlab("Length of Bottlenose Dolphins Strandings") +
ylab("Presence of Wind Turbines") +
scale_y_continuous(breaks = c(0, 1), labels = c("No", "Yes"),limits = c(0,1))
fit_2_plot

#Fitting a regression model (Wind Turbine presence & Weight)
fit_3 <- glm(turbine_presence~Length+Weight,family='binomial', data = cleaned_strandings)
#Summary of the regression model fit_2
summary(fit_3)

#Log odds of turbines presence
cleaned_strandings$log_odds_turbines<-predict(fit_3,type="link")
#Plot for fit_2
fit_3_plot <- ggplot(cleaned_strandings, aes(x =Length,y=log_odds_turbines, color=Weight)) +
geom_point(shape = 1) +
geom_smooth(method=glm)+
xlab("Weight of Bottlenose Dolphins Strandings") +
ylab("Presence of Wind Turbines")
#Plot
fit_3_plot

# use to find difference in length in states 
diff_length <- lm(Length ~ State, data = cleaned_strandings_test)
#summary of linear regression
summary(diff_length)

#use mutate to create state binary variables
turbine_data <- turbine_data %>%
  mutate(
    VA = ifelse(State == "VA", 1, 0),
    NY = ifelse(State == "NY", 1, 0),
    RI = ifelse(State == "RI", 1, 0),
    MA = ifelse(State == "MA", 1, 0))

#creating a linear regression model
fit_6 <- lm(Length ~ VA + NY + RI + MA, data = turbine_data)
#summary of linear regression
summary(fit_6)

#finding the mean of length within VA
mean_length_VA <- mean(turbine_data$Length[turbine_data$VA == "1"])
mean_length_VA

#finding the mean of length within VA
mean_length_NY <- mean(turbine_data$Length[turbine_data$NY == "1"])
mean_length_NY

#finding the mean of length within VA
mean_length_RI <- mean(turbine_data$Length[turbine_data$RI == "1"])
mean_length_RI

#finding the mean of length within VA
mean_length_MA <- mean(turbine_data$Length[turbine_data$MA == "1"])
mean_length_MA

#plot of data
plot6 <- ggplot(turbine_data, aes(x = State, y = Length, color=State)) +
    geom_point(shape = 1) +
    geom_hline(yintercept = 260.8889, color = "red") +
    geom_hline(yintercept = 200.9059, color = "forestgreen") +
    geom_hline(yintercept = 303, color = "skyblue") +
    geom_hline(yintercept = 184.6717, color = "purple") +

  xlab("State") +
  ylab("Length (cm)") +
  ggtitle("Linear Regression of Length across Offshore Wind States") +
  labs(color = "States") +
theme_bw()
plot6


```

```{r understanding data}
#remove unneeded covariates
cleaned_strandings_test <- subset(strandings, select = -c(Shot, Fishery.Interaction, Boat.Collision, Weight))

#remove NAs
cleaned_strandings_test <- na.omit(cleaned_strandings_test)

#removing blanks in Age.Class
cleaned_strandings_test <- cleaned_strandings_test[!grepl("^\\s*$", cleaned_strandings_test$Age.Class), ]
#removing unknowns in Age.Class
cleaned_strandings_test <- cleaned_strandings_test[!cleaned_strandings_test$Age.Class %in% c("UNKNOWN"), ]
#removing unknowns in Sex
cleaned_strandings_test <- cleaned_strandings_test[!cleaned_strandings_test$Sex %in% c("UNKNOWN"), ]

#create binary covariate for wind turbine presence in state
cleaned_strandings_test <- cleaned_strandings_test %>%
  mutate(turbine_presence = if_else(State %in% c("VA", "NY", "RI", "MA"), 1, 0))

#count of strandings in wind farm states = 80
sum(cleaned_strandings_test$turbine_presence)

#create offshore wind subset
turbine_data <- cleaned_strandings_test[cleaned_strandings_test$State %in% c("VA", "NY", "RI", "MA"), ]

#covarients used: states, turbine presence, sex, length, age class

#States info
table(cleaned_strandings_test$State)
# 15 states included
# Most strandings were in Florida (295) and Texas (306)
# Least were in Maine (1) and Rhode Island (1)
# States with offshore wind: Virginia, New York, Rhode Island, and Massachusetts 

#count of strandings in wind farm states = 80
sum(cleaned_strandings_test$turbine_presence)

#Length info
# average overall length 194.2091 
mean(cleaned_strandings_test$Length)
# average offshore wind length = 198.175
mean(turbine_data$Length)

#reordering age classes so they are from youngest to oldest
age_class_order <- c("PUP/CALF", "YEARLING", "SUBADULT", "ADULT")

#summary graph of Age Class by Length
length_ageclass <- ggplot(cleaned_strandings_test, aes(x = factor(Age.Class, levels = age_class_order), y = Length)) +
  geom_boxplot(fill="skyblue") +
  labs(x = "Age Class", y = "Length (cm)") +
  ggtitle("Dolphin Length by Age Class")
length_ageclass

#plot of Lengths in each state
state_length <- ggplot(cleaned_strandings_test, aes(x = State, y = Length)) +
  geom_boxplot(fill="skyblue") +
  labs(x = "States", y = "Length (cm)") +
  ggtitle("Dolphin Length by State")
state_length

#plot of Lengths in each offshore wind state
turbinestate_length <- ggplot(turbine_data, aes(x = State, y = Length)) +
  geom_boxplot(fill="skyblue") +
  labs(x = "States", y = "Length (cm)") +
  ggtitle("Dolphin Length by State")
turbinestate_length

#plot of number of strandings for each offshore wind state
standings_wf_state <- ggplot(turbine_data, aes(x = State)) +
  geom_bar(fill = "skyblue") +
  labs(x = "States", y = "Number of Strandings") +
  ggtitle("Number of Dolphin Strandings by Offshore Wind States")
standings_wf_state

#plot of number of strandings for each offshore wind state
standings_state <- ggplot(cleaned_strandings_test, aes(x = State)) +
  geom_bar(fill = "skyblue") +
  labs(x = "States", y = "Number of Strandings") +
  ggtitle("Number of Dolphin Strandings by Offshore Wind States")
standings_state

#plot of the number of strandings in each age class
strandings_ageclass <- ggplot(cleaned_strandings_test, aes(x = factor(Age.Class, levels = age_class_order), fill = factor(turbine_presence))) +
  geom_bar(position = "stack") +
  labs(x = "Age Class", y = "Count", fill = "Presence of Turbines") +
  ggtitle("Age Class vs Presence of Turbines")
strandings_ageclass

#plot of the number of strandings in each sex
strandings_sex <- ggplot(cleaned_strandings_test, aes(x = factor(Sex), fill = factor(turbine_presence))) +
  geom_bar(position = "stack") +
  labs(x = "Sex", y = "Count", fill = "Presence of Turbines") +
  ggtitle("Sex vs Presence of Turbines")
strandings_sex

```

